# resources that will be deployed by the job
resources:
  # dashboard
  - ../../charts/dashboard/templates/default-roles.yaml
  - ../../charts/dashboard/templates/webhook.yaml

  # stack
  - ../../charts/stack/templates/acme-issuer.yaml

  # cert manager
  - ../../charts/stack/charts/cert-manager/charts/webhook/templates/apiservice.yaml
  - ../../charts/stack/charts/cert-manager/charts/webhook/templates/validating-webhook.yaml


commonLabels:
  "dashboard.presslabs.com/version": "0.0.1"


patchesJson6902:
# cert-manager set owner reference
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: ValidatingWebhookConfiguration
    name: ${name}-cert-manager-webhook
  path: owner_reference_patch.yaml

# dashboard
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: ValidatingWebhookConfiguration
    name: ${name}-dashboard
  path: owner_reference_patch.yaml

# stack
- target:
    group: certmanager.k8s.io
    version: v1alpha1
    kind: ClusterIssuer
    name: ${name}-default
  path: owner_reference_patch.yaml
