applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  # general
  serviceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin

  # tag used for docker images
  tag:
    type: string
    default: $TAG

  appUID:
    type: string
    x-google-marketplace:
      type: APPLICATION_UID

  # dashboard
  dashboardDomain:
    type: string
  dashboardImage:
    type: string
    default: $REGISTRY/dashboard
    x-google-marketplace:
      type: IMAGE
  dashboardProjectID:
    type: string
    default: ""
  dashboardServiceAccountKey:
    type: string
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: explicitPasswordEncoded
  dashboardOIDCClientID:
    type: string
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: explicitPasswordEncoded
  dashboardOIDCSecret:
    type: string
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: explicitPasswordEncoded
  dashboardOIDCIssuer:
    type: string
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: explicitPasswordEncoded
  dashboardSentryDSN:
    type: string
    default: ''

  # cert-manager
  certManagerImage:
    type: string
    default: $REGISTRY/cert-manager-controller
    x-google-marketplace:
      type: IMAGE
  certAcmeSolverImage:
    type: string
    default: $REGISTRY/cert-manager-acmesolver
    x-google-marketplace:
      type: IMAGE
  certWebhookImage:
    type: string
    default: $REGISTRY/cert-manager-webhook
    x-google-marketplace:
      type: IMAGE
  certCAinjectorImage:
    type: string
    default: $REGISTRY/cert-manager-cainjector
    x-google-marketplace:
      type: IMAGE

  # prometheus operator
  promOperatorImage:
    type: string
    default: $REGISTRY/prometheus-operator
    x-google-marketplace:
      type: IMAGE
  promConfigMapReloadImage:
    type: string
    default: $REGISTRY/prometheus-configmap-reload
    x-google-marketplace:
      type: IMAGE
  promConfigReloaderImage:
    type: string
    default: $REGISTRY/prometheus-config-reloader
    x-google-marketplace:
      type: IMAGE
  promImage:
    type: string
    default: $REGISTRY/prometheus-prometheus
    x-google-marketplace:
      type: IMAGE

  # ingress controller
  ingressImage:
    type: string
    default: $REGISTRY/ingress-controller
    x-google-marketplace:
      type: IMAGE
  ingressDefaultBackendImage:
    type: string
    default: $REGISTRY/ingress-default-backend
    x-google-marketplace:
      type: IMAGE

  # mysql-operator
  mysqlControllerImage:
    type: string
    default: $REGISTRY/mysql-operator
    x-google-marketplace:
      type: IMAGE
  mysqlOrchestratorImage:
    type: string
    default: $REGISTRY/mysql-orchestrator
    x-google-marketplace:
      type: IMAGE
  mysqlSidecarImage:
    type: string
    default: $REGISTRY/mysql-sidecar
    x-google-marketplace:
      type: IMAGE
  mysqlMetricsImage:
    type: string
    default: $REGISTRY/mysql-metrics
    x-google-marketplace:
      type: IMAGE
  mysqlPerconaImage:
    type: string
    default: $REGISTRY/mysql-percona
    x-google-marketplace:
      type: IMAGE
  mysqlOrchestratorPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        includeSymbols: False
        base64: True

  # wordpress operator
  wordpressOperatorImage:
    type: string
    default: $REGISTRY/wordpress-operator
    x-google-marketplace:
      type: IMAGE
  wordpressRuntimeImage:
    type: string
    default: $REGISTRY/wordpress-runtime
    x-google-marketplace:
      type: IMAGE
  wordpressRcloneImage:
    type: string
    default: $REGISTRY/wordpress-rclone
    x-google-marketplace:
      type: IMAGE
  wordpressGitCloneImage:
    type: string
    default: $REGISTRY/wordpress-gitclone
    x-google-marketplace:
      type: IMAGE

  # let's encrypt
  letsEncryptEmail:
    type: string
    default: 'ping@example.com'

  letsEncryptServer:
    type: string
    default: 'https://acme-v02.api.letsencrypt.org/directory'
    enum:
      - 'https://acme-v02.api.letsencrypt.org/directory'
      - 'https://acme-staging-v02.api.letsencrypt.org/directory'

  # miscellaneous
  kubectlImage:
    type: string
    default: $REGISTRY/kubectl:$TAG
    x-google-marketplace:
      type: IMAGE


required:
- name
- namespace
- dashboardDomain
- dashboardServiceAccountKey
- dashboardOIDCClientID
- dashboardOIDCSecret
- dashboardOIDCIssuer
- dashboardProjectID
