applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  # general
  serviceAccount:
    type: string
    title: Service Account
    description: The service account used for all application's workloads
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin

  appUID:
    type: string
    title: Application UID
    description: The uuid of the created Application object. Not required
    x-google-marketplace:
      type: APPLICATION_UID

  # dashboard
  dashboardDomain:
    type: string
    title: Domain
    description: Use to connect to the dashboard interface. This host is set in the ingress
  dashboardImage:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  dashboardProjectID:
    type: string
    title: Project ID
    description: The project ID where the application will be installed. This is used for provisioning other Google services.
    default: ""
  dashboardServiceAccountKey:
    type: string
    title: Service Account Key
    description: A service account key in JSON format. This service account is used for provisioning other Google services.
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: explicitPasswordEncoded
  dashboardOIDCClientID:
    type: string
    title: OpenID Connect ID
    description: OIDC client ID
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: explicitPasswordEncoded
  dashboardOIDCSecret:
    type: string
    title: OpenID Connect Secret
    description: OIDC client Secret
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: explicitPasswordEncoded
  dashboardOIDCIssuer:
    type: string
    title: OpenID Connect Issuer
    description: OIDC Issuer
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: explicitPasswordEncoded

  # cert-manager
  certManagerImage:
    type: string
    default: $REGISTRY/cert-manager-controller:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: certManagerImageRegistry
            after: certManagerImageTag
  certAcmeSolverImage:
    type: string
    default: $REGISTRY/cert-manager-acmesolver:$TAG
    x-google-marketplace:
      type: IMAGE
  certWebhookImage:
    type: string
    default: $REGISTRY/cert-manager-webhook:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: certWebhookImageRegistry
            after: certWebhookImageTag
  certCAinjectorImage:
    type: string
    default: $REGISTRY/cert-manager-cainjector:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: certCAinjectorImageRegistry
            after: certCAinjectorImageTag

  # prometheus operator
  promOperatorImage:
    type: string
    default: $REGISTRY/prometheus-operator:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: promOperatorImageRegistry
            after: promOperatorImageTag

  # ingress controller
  ingressImage:
    type: string
    default: $REGISTRY/ingress-controller:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: ingressImageRegistry
            after: ingressImageTag
  ingressDefaultBackendImage:
    type: string
    default: $REGISTRY/ingress-default-backend:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: ingressDefaultBackendImageRegistry
            after: ingressDefaultBackendImageTag

  # mysql-operator
  mysqlControllerImage:
    type: string
    default: $REGISTRY/mysql-operator:$TAG
    x-google-marketplace:
      type: IMAGE
  mysqlOrchestratorImage:
    type: string
    default: $REGISTRY/mysql-orchestrator:$TAG
    x-google-marketplace:
      type: IMAGE

  mysqlOrchestratorPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        includeSymbols: False
        base64: True

  # wordpress operator
  wordpressOperatorImage:
    type: string
    default: $REGISTRY/wordpress-operator:$TAG
    x-google-marketplace:
      type: IMAGE

  # let's encrypt
  letsEncryptEmail:
    type: string
    title: Let's Encrypt Email
    description: The email used for the ACME account contact informations.
    default: 'ping@example.com'

  letsEncryptServer:
    type: string
    title: Let's Encrypt Server
    description: The Let's Encrypt API endpoint
    default: 'https://acme-v02.api.letsencrypt.org/directory'
    enum:
      - 'https://acme-v02.api.letsencrypt.org/directory'
      - 'https://acme-staging-v02.api.letsencrypt.org/directory'

  # miscellaneous
  kubectlImage:
    type: string
    default: $REGISTRY/kubectl:$TAG
    x-google-marketplace:
      type: IMAGE

  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET


required:
- name
- namespace
- dashboardDomain
- dashboardServiceAccountKey
- dashboardOIDCClientID
- dashboardOIDCSecret
- dashboardOIDCIssuer
- dashboardProjectID
