applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  serviceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin

  certManagerImage:
    type: string
    default: $REGISTRY/cert-manager-controller:$TAG
    x-google-marketplace:
      type: IMAGE

  acmeSolverImage:
    type: string
    default: $REGISTRY/acme-ingress-shim:$TAG
    x-google-marketplace:
      type: IMAGE

required:
- name
- namespace
