applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  # general
  serviceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin

  appUID:
    type: string
    x-google-marketplace:
      type: APPLICATION_UID

  # dashboard
  dashboardDomain:
    type: string
  dashboardImage:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  dashboardProjectID:
    type: string
    default: ""
  dashboardServiceAccountKey:
    type: string
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: explicitPasswordEncoded
  dashboardOIDCClientID:
    type: string
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: explicitPasswordEncoded
  dashboardOIDCSecret:
    type: string
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: explicitPasswordEncoded
  dashboardOIDCIssuer:
    type: string
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: explicitPasswordEncoded
  dashboardSentryDSN:
    type: string
    default: '""'

  # cert-manager
  certManagerImage:
    type: string
    default: $REGISTRY/cert-manager-controller:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: certManagerImageRegistry
            after: certManagerImageTag
  certAcmeSolverImage:
    type: string
    default: $REGISTRY/cert-manager-acmesolver:$TAG
    x-google-marketplace:
      type: IMAGE
  certWebhookImage:
    type: string
    default: $REGISTRY/cert-manager-webhook:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: certWebhookImageRegistry
            after: certWebhookImageTag
  certCAinjectorImage:
    type: string
    default: $REGISTRY/cert-manager-cainjector:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: certCAinjectorImageRegistry
            after: certCAinjectorImageTag

  # prometheus operator
  promOperatorImage:
    type: string
    default: $REGISTRY/prometheus-operator:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: promOperatorImageRegistry
            after: promOperatorImageTag

  # ingress controller
  ingressImage:
    type: string
    default: $REGISTRY/ingress-controller:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: ingressImageRegistry
            after: ingressImageTag
  ingressDefaultBackendImage:
    type: string
    default: $REGISTRY/ingress-default-backend:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: ingressDefaultBackendImageRegistry
            after: ingressDefaultBackendImageTag

  # mysql-operator
  mysqlControllerImage:
    type: string
    default: $REGISTRY/mysql-operator:$TAG
    x-google-marketplace:
      type: IMAGE
  mysqlOrchestratorImage:
    type: string
    default: $REGISTRY/mysql-orchestrator:$TAG
    x-google-marketplace:
      type: IMAGE

  mysqlOrchestratorPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        includeSymbols: False
        base64: True

  # wordpress operator
  wordpressOperatorImage:
    type: string
    default: $REGISTRY/wordpress-operator:$TAG
    x-google-marketplace:
      type: IMAGE

  # let's encrypt
  letsEncryptEmail:
    type: string
    default: 'ping@example.com'

  letsEncryptServer:
    type: string
    default: 'https://acme-v02.api.letsencrypt.org/directory'
    enum:
      - 'https://acme-v02.api.letsencrypt.org/directory'
      - 'https://acme-staging-v02.api.letsencrypt.org/directory'

  # miscellaneous
  kubectlImage:
    type: string
    default: $REGISTRY/kubectl:$TAG
    x-google-marketplace:
      type: IMAGE


required:
- name
- namespace
- dashboardDomain
- dashboardServiceAccountKey
- dashboardOIDCClientID
- dashboardOIDCSecret
- dashboardOIDCIssuer
- dashboardProjectID
