applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  # general
  serviceAccount:
    type: string
    title: Presslabs Dashboard Service Account
    description: Service account that will be assigned to the Presslabs Dashboard.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin

  # dashboard
  dashboardDomain:
    type: string
    title: Presslabs Dashboard Domain
    description: This will be the domain used by the Presslabs Dashboard.
    default: example.com
    maxLength: 253
    pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$"

  dashboardIP:
    type: string
    default: ""
    title: Presslabs Dashboard Ingress IP Address
    description: |
      We recommend that you create a pre-allocated static IP address for your Presslabs Dashboard to prevent IP changes.
      If not specified, an ephemeral external IP will be created which you can later convert to a static one.
      Read more about it at https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address.

  dashboardImage:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE

  gcpWorkloadIdentityEnabled:
    type: boolean
    default: false
    title: I acknowledge that Workload Identity must be enabled for Presslabs Dashboard to function properly
    description: Presslabs Dashboard requires Workload Identity to be enabled for nodes running it's workloads.

  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET

  #
  # Container Images
  #

  kubectlImage:
    type: string
    default: $REGISTRY/k8s-deploy-tools:$TAG
    x-google-marketplace:
      type: IMAGE

  stackInstallerImage:
    type: string
    default: $REGISTRY/stack-installer:$TAG
    x-google-marketplace:
      type: IMAGE


required:
- name
- namespace
- dashboardDomain
- gcpWorkloadIdentityEnabled

x-google-marketplace:
  clusterConstraints:
    resources:
    - replicas: 3
      requests:
        cpu: 1
        memory: 3Gi
      affinity:
        simpleNodeAffinity:
          type: REQUIRE_ONE_NODE_PER_REPLICA
