applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  # general
  serviceAccount:
    type: string
    title: Presslabs Dashboard Service Account
    description: Service account that will be assigned to the Presslabs Dashboard.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin

  # dashboard
  dashboardDomain:
    type: string
    title: Presslabs Dashboard Domain
    description: This will be the domain used by the Presslabs Dashboard.
    default: example.com

  dashboardIP:
    type: string
    default: ""
    title: Presslabs Dashboard Ingress IP Address
    description: |
      We recommend that you create a pre-allocated static IP address for your Presslabs Dashboard to prevent IP changes.
      If not specified, an ephemeral external IP will be created which you can later convert to a static one.
      Read more about it at https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address.

  dashboardAdminEmails:
    type: string
    title: Presslabs Dashboard Admins
    description: A comma-separated list of emails for users with elevated access to the Presslabs Dashboard. These users gain a cluster-admin role for Dashboard's operations.
    default: ""

  dashboardImage:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE

  dashboardOIDCClientID:
    type: string
    title: Auth0 Client ID
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: dashboardOIDCClientIDEncoded

  dashboardOIDCSecret:
    type: string
    title: Auth0 Client Secret
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: dashboardOIDCSecretEncoded

  dashboardOIDCIssuer:
    type: string
    title: Auth0 Issuer URL
    description: The Auth0 domain, including the https:// prefix and trailing slash.
    default: "https://example.auth0.com/"
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: dashboardOIDCIssuerEncoded

  # let's encrypt
  letsEncryptEmail:
    type: string
    title: Let's Encrypt Account Email
    description: Let's Encrypt will use this to contact you about expiring certificates and issues related to your account.
    default: 'ping@example.com'

  letsEncryptServer:
    type: string
    title: Let's Encrypt Server
    description: Select between Let's Encrypt staging and live endpoints.
    default: 'https://acme-v02.api.letsencrypt.org/directory'
    enum:
      - 'https://acme-v02.api.letsencrypt.org/directory'
      - 'https://acme-staging-v02.api.letsencrypt.org/directory'

  gcpConfigConnectorEnabled:
    type: boolean
    default: false
    title: I acknowledge that Config Connector must be installed for Presslabs Dashboard to function properly
    description: Presslabs Dashboard requires that Config Connector is installed in order to function properly.

  gcpWorkloadIdentityEnabled:
    type: boolean
    default: false
    title: I acknowledge that Workload Identity must be enabled for Presslabs Dashboard to function properly
    description: Presslabs Dashboard requires Workload Identity to be enabled for nodes running it's workloads.

  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET

  #
  # Container Images
  #

  # cert-manager
  certManagerImage:
    type: string
    default: $REGISTRY/cert-manager-controller:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: certManagerImageRegistry
            after: certManagerImageTag

  certAcmeSolverImage:
    type: string
    default: $REGISTRY/cert-manager-acmesolver:$TAG
    x-google-marketplace:
      type: IMAGE

  certWebhookImage:
    type: string
    default: $REGISTRY/cert-manager-webhook:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: certWebhookImageRegistry
            after: certWebhookImageTag

  certCAinjectorImage:
    type: string
    default: $REGISTRY/cert-manager-cainjector:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: certCAinjectorImageRegistry
            after: certCAinjectorImageTag

  # ingress controller
  ingressImage:
    type: string
    default: $REGISTRY/ingress-controller:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: ingressImageRegistry
            after: ingressImageTag

  ingressDefaultBackendImage:
    type: string
    default: $REGISTRY/ingress-default-backend:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: ingressDefaultBackendImageRegistry
            after: ingressDefaultBackendImageTag

  # mysql-operator
  mysqlControllerImage:
    type: string
    default: $REGISTRY/mysql-operator:$TAG
    x-google-marketplace:
      type: IMAGE

  mysqlOrchestratorImage:
    type: string
    default: $REGISTRY/mysql-orchestrator:$TAG
    x-google-marketplace:
      type: IMAGE

  mysqlOrchestratorPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        includeSymbols: False
        base64: True

  # wordpress operator
  wordpressOperatorImage:
    type: string
    default: $REGISTRY/wordpress-operator:$TAG
    x-google-marketplace:
      type: IMAGE

  # miscellaneous
  kubectlImage:
    type: string
    default: $REGISTRY/k8s-deploy-tools:$TAG
    x-google-marketplace:
      type: IMAGE

required:
- name
- namespace
- dashboardDomain
- dashboardOIDCClientID
- dashboardOIDCSecret
- dashboardOIDCIssuer
- dashboardAdminEmails
- gcpConfigConnectorEnabled
- gcpWorkloadIdentityEnabled
