x-google-marketplace:
  schemaVersion: v2

  # MUST match the version of the Application custom resource object.
  applicationApiVersion: v1beta1

  # The release version is required in the schema and MUST match the
  # release tag on the the deployer.
  publishedVersion: $TAG
  publishedVersionMetadata:
    releaseNote: >
      TBD

    # releaseTypes list is optional.
    # "Security" should only be used if this is an important update to patch
    # an existing vulnerability, as such updates will display more prominently for users.
    # releaseTypes:
    # - Feature
    # - BugFix
    # - Security
    releaseTypes:

    # If "recommended" is "true", users using older releases are encouraged
    # to update as soon as possible. This is useful if, for example, this release
    # fixes a critical issue.
    # recommended: true

  images:
    "":
      properties:
        imageDashboardFull:
          type: FULL

    k8s-deploy-tools:
      properties:
        imageK8sDeployToolsFull:
          type: FULL
        deployerTag:
          type: TAG

    stack-installer:
      properties:
        imageStackInstallerFull:
          type: FULL


  clusterConstraints:
    k8sVersion: '>=1.17.0'
    resources:
    - replicas: 3
      requests:
        cpu: 1300m # total to ~ 4 CPU
        memory: 2600M # total to ~ 8GB


properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  # general
  serviceAccount:
    type: string
    title: Presslabs Dashboard Service Account
    description: Service account that will be assigned to the Presslabs Dashboard.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          This service account is used to deploy cluster-wide multiple components in order to run
          Presslabs Dashboard. The requested permission is cluster-admin.

          Is used to install Presslabs Stack in presslabs-system namespace, to install custom CRDs, to
          install Cert Manager, to configure cluster-wide webhooks, and to install RBAC roles needed
          to operate the Dashboard.

        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: view
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['apiextensions.k8s.io']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['rbac.authorization.k8s.io']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['admissionregistration.k8s.io']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['apps']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['policy']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['app.k8s.io']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['cert-manager.io']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['monitoring.coreos.com']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['batch']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['storage.k8s.io']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['scheduling.k8s.io']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['dashboard.presslabs.com']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['wordpress.presslabs.org']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['mysql.presslabs.org']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['iam.cnrm.cloud.google.com']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['storage.cnrm.cloud.google.com']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['networking.k8s.io']
            resources: ['*']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['autoscaling']
            resources: ['*']
            verbs: ['*']

  # dashboard
  dashboardDomain:
    type: string
    title: Presslabs Dashboard Domain
    description: This will be the domain used by the Presslabs Dashboard.
    default: example.com
    maxLength: 253
    pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$"

  dashboardIP:
    type: string
    default: ""
    title: Presslabs Dashboard Ingress IP Address
    description: |
      We recommend that you create a pre-allocated static IP address for your Presslabs Dashboard to prevent IP changes.
      If not specified, an ephemeral external IP will be created which you can later convert to a static one.
      Read more about it at https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address.

  gcpWorkloadIdentityEnabled:
    type: boolean
    default: false
    title: I acknowledge that Workload Identity must be enabled for Presslabs Dashboard to function properly
    description: Presslabs Dashboard requires Workload Identity to be enabled for nodes running it's workloads.

  gcpApplicationManagerEnabled:
    type: boolean
    default: false
    title: I acknowledge that Application Manager addon must be enabled for Presslabs Dashboard to function properly
    description: Presslabs Dashboard requires Application Manager addon to be enabled to see the proper system status.

  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET


required:
- name
- namespace
- dashboardDomain
- gcpWorkloadIdentityEnabled
- gcpApplicationManagerEnabled
