applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  serviceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin

  certManagerImage:
    type: string
    default: $REGISTRY/cert-manager-controller
    x-google-marketplace:
      type: IMAGE

  certAcmeSolverImage:
    type: string
    default: $REGISTRY/cert-manager-acmesolver
    x-google-marketplace:
      type: IMAGE

  certWebhookImage:
    type: string
    default: $REGISTRY/cert-manager-webhook
    x-google-marketplace:
      type: IMAGE

  certCAinjectorImage:
    type: string
    default: $REGISTRY/cert-manager-cainjector
    x-google-marketplace:
      type: IMAGE

  # tag used for docker images
  tag:
    type: string
    default: $TAG

  appUID:
    type: string
    x-google-marketplace:
      type: APPLICATION_UID

required:
- name
- namespace
