x-google-marketplace:
  schemaVersion: v2

  # MUST match the version of the Application custom resource object.
  applicationApiVersion: v1beta1

  # The release version is required in the schema and MUST match the
  # release tag on the the deployer.
  publishedVersion: $TAG
  publishedVersionMetadata:
    releaseNote: >-
      TODO Release 0.5 note.

    # releaseTypes list is optional.
    # "Security" should only be used if this is an important update to patch
    # an existing vulnerability, as such updates will display more prominently for users.
    # releaseTypes:
    # - Feature
    # - BugFix
    # - Security

    # If "recommended" is "true", users using older releases are encouraged
    # to update as soon as possible. This is useful if, for example, this release
    # fixes a critical issue.
    # recommended: true

  images:
    "":
      properties:
        imageDashboardFull:
          type: FULL

    k8s-deploy-tools:
      properties:
        imageK8sDeployToolsFull:
          type: FULL
        deployerTag:
          type: TAG

    stack-installer:
      properties:
        imageStackInstallerFull:
          type: FULL


  clusterConstraints:
    resources:
    - replicas: 3
      requests:
        cpu: 1
        memory: 3Gi
      affinity:
        simpleNodeAffinity:
          type: REQUIRE_ONE_NODE_PER_REPLICA


properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  # general
  serviceAccount:
    type: string
    title: Presslabs Dashboard Service Account
    description: Service account that will be assigned to the Presslabs Dashboard.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Service account that will be assigned to the Presslabs Dashboard.
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin

  # dashboard
  dashboardDomain:
    type: string
    title: Presslabs Dashboard Domain
    description: This will be the domain used by the Presslabs Dashboard.
    default: example.com
    maxLength: 253
    pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$"

  dashboardIP:
    type: string
    default: ""
    title: Presslabs Dashboard Ingress IP Address
    description: |
      We recommend that you create a pre-allocated static IP address for your Presslabs Dashboard to prevent IP changes.
      If not specified, an ephemeral external IP will be created which you can later convert to a static one.
      Read more about it at https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address.

  gcpWorkloadIdentityEnabled:
    type: boolean
    default: false
    title: I acknowledge that Workload Identity must be enabled for Presslabs Dashboard to function properly
    description: Presslabs Dashboard requires Workload Identity to be enabled for nodes running it's workloads.

  gcpApplicationManagerEnabled:
    type: boolean
    default: false
    title: I acknowledge that Application Manager addon must be enabled for Presslabs Dashboard to function properly
    description: Presslabs Dashboard requires Application Manager addon to be enabled to see the proper system status.

  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET


required:
- name
- namespace
- dashboardDomain
- gcpWorkloadIdentityEnabled
- gcpApplicationManagerEnabled
