apiVersion: batch/v1
kind: Job
metadata:
  name: "${name}-dash-install-stack"
spec:
  template:
    spec:
      serviceAccountName: $serviceAccount
      restartPolicy: Never
      containers:
      - name: installer
        image: $imageStackInstallerFull
        env:
        - name: NAMESPACE
          value: presslabs-system

        volumeMounts:
        - name: values-yaml
          mountPath: /config

      volumes:
      - name: values-yaml
        configMap:
          name: "${name}-stack-values"


  backoffLimit: 3
