# resources that will be deployed by the deploy
resources:
  - application.yaml

  # dashboard
  - ../charts/dashboard-gcm/charts/dashboard/templates/apiserver-deployment.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/apiserver-ingress.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/apiserver-oidc-secret.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/apiserver-service.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/apiserver-sentry-secret.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/controller-deployment.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/webhook-service.yaml

  # cert-manager objects
  - ../charts/dashboard-gcm/charts/stack/charts/cert-manager/templates/webhook-service.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/cert-manager/templates/webhook-deployment.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/cert-manager/charts/cainjector/templates/deployment.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/cert-manager/templates/deployment.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/cert-manager/templates/service.yaml

  # nginx-ingress controller
  - ../charts/dashboard-gcm/charts/stack/charts/nginx-ingress/templates/controller-deployment.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/nginx-ingress/templates/controller-configmap.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/nginx-ingress/templates/controller-service.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/nginx-ingress/templates/default-backend-deployment.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/nginx-ingress/templates/default-backend-service.yaml

  # mysql operator
  - ../charts/dashboard-gcm/charts/stack/charts/mysql-operator/templates/statefulset.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/mysql-operator/templates/orc-service.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/mysql-operator/templates/orc-secret.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/mysql-operator/templates/orc-config.yaml

  # wordpress operator
  - ../charts/dashboard-gcm/charts/stack/charts/wordpress-operator/templates/deployment.yaml


patchesJson6902:
# cert-manager fix service accounts
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ${name}-cert-manager-cainjector
  path: patches/service_account_patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ${name}-cert-manager-webhook
  path: patches/service_account_patch.yaml

# nginx-ingress controller image tag patch
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ${name}-nginx-ingress-controller
  path: patches/ingress_image_tag.yaml

# mysql-operator passwords
- target:
    version: v1
    kind: Secret
    name: ${name}-mysql-operator-orc
  path: patches/mysql_secret.yaml

# dashboard secrets to bypass base64 encode
- target:
    version: v1
    kind: Secret
    name: ${name}-dashboard-oidc
  path: patches/dashboard_oidc_secret.yaml
