# resources that will be deployed by the deploy
resources:
  - ../charts/stack/templates/application.yaml

  # dashbaord
  - ../charts/dashboard/templates/apiserver-deployment.yaml
  # TODO: uncomment when ingress is configured
  #- ../charts/dashboard/templates/apiserver-ingress.yaml
  - ../charts/dashboard/templates/apiserver-oidc-secret.yaml
  - ../charts/dashboard/templates/apiserver-service.yaml
  - ../charts/dashboard/templates/controller-deployment.yaml
  - ../charts/dashboard/templates/controller-gcloud-serviceaccount.yaml

  # cert-manager objects
  - ../charts/stack/charts/cert-manager/charts/webhook/templates/service.yaml
  - ../charts/stack/charts/cert-manager/charts/webhook/templates/deployment.yaml
  - ../charts/stack/charts/cert-manager/charts/cainjector/templates/deployment.yaml
  - ../charts/stack/charts/cert-manager/templates/deployment.yaml

  # prometheus-operator objects
  - ../charts/stack/charts/prometheus-operator/templates/prometheus-operator/service.yaml
  - ../charts/stack/charts/prometheus-operator/templates/prometheus-operator/deployment.yaml

  - ../charts/stack/charts/prometheus-operator/templates/prometheus/service.yaml

  # nginx-ingress controller
  - ../charts/stack/charts/nginx-ingress/templates/controller-deployment.yaml
  - ../charts/stack/charts/nginx-ingress/templates/controller-configmap.yaml
  - ../charts/stack/charts/nginx-ingress/templates/controller-service.yaml
  - ../charts/stack/charts/nginx-ingress/templates/default-backend-deployment.yaml
  - ../charts/stack/charts/nginx-ingress/templates/default-backend-service.yaml

  # mysql operator
  - ../charts/stack/charts/mysql-operator/templates/statefulset.yaml
  - ../charts/stack/charts/mysql-operator/templates/orc-service.yaml
  - ../charts/stack/charts/mysql-operator/templates/orc-secret.yaml
  - ../charts/stack/charts/mysql-operator/templates/orc-config.yaml

  # wordpress operator
  - ../charts/stack/charts/wordpress-operator/templates/deployment.yaml


patchesJson6902:
# cert-manager fix service accounts
- target:
    group: apps
    version: v1beta1
    kind: Deployment
    name: "${name}-cert-inj"
  path: service_account_patch.yaml
- target:
    group: apps
    version: v1beta1
    kind: Deployment
    name: "${name}-cert-wh"
  path: service_account_patch.yaml
# nginx-ingress controller image tag patch
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: ${name}-nginx-ingress-controller
  path: ingress_image_tag.yaml
