apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orchestrator.fullname" . }}
  labels:
    app: {{ template "orchestrator.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  TOPOLOGY_USER: {{ printf "%s" .Values.topologyUser | b64enc | quote }}
  {{- if .Values.topologyPassword }}
  TOPOLOGY_PASSWORD: {{ printf "%s" .Values.topologyPassword | b64enc | quote }}
  {{- else }}
  TOPOLOGY_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
