apiVersion: batch/v1
kind: Job
metadata:
  name: "${name}-dash-install-manifest"
spec:
  template:
    spec:
      serviceAccountName: $serviceAccount
      restartPolicy: Never
      containers:
      - name: init
        image: $kubectlImage
        command: ["/bin/sh", "-c"]
        args:
          - |
            # first install CRDs
            cat /data/crds/manifest_crds.yaml.gz.b64enc | base64 -d | gzip -dc | kubectl apply -f- ;
            # don't validate due to: https://github.com/jetstack/cert-manager/issues/1143
            kubectl apply --validate=false -f /data/globals/manifest_globals.yaml ;
        volumeMounts:
        - name: globals-manifests
          mountPath: /data/globals/
        - name: crd-manifests
          mountPath: /data/crds/
      volumes:
      - name: globals-manifests
        configMap:
          name: "${name}-dash-globals-manifests"
      - name: crd-manifests
        configMap:
          name: "${name}-dash-crds-manifests"

  backoffLimit: 3
