apiVersion: v1
kind: Namespace
metadata:
  name: "${namespace}"
  labels:
    # avoid chicken-and-egg problem by disabling issuer validation in this namespace
    certmanager.k8s.io/disable-validation: "true"
