resources:
  requests:
    memory: "128Mi"
    cpu: "50m"

webhook:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"

cainjector:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
