component_default: &component_default
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"

global:
  leaderElection:
    namespace: ${namespace}

dashboard:
  image: $dashboardImage
  fullNameOverride: "${name}-dashboard"

  stack:
    name: stack
    namespace: presslabs-system

  defaults:
    installRoles: true

  crd:
    install: true

  apiserver:
    <<: *component_default

    baseURL: https://$dashboardDomain

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: presslabs-stack
        cert-manager.io/cluster-issuer: stack-default-certificate-issuer
      hosts:
        - $dashboardDomain
      tls:
        - secretName: ${name}-dashboard-tls
          hosts:
            - $dashboardDomain
    serviceAccount:
      create: false
      name: $serviceAccount

    extraArgs:
      - --locales-path=/pkg/locales

  controller:
    <<: *component_default
    enablePrometheusIntegration: false
    serviceAccount:
      create: false
      name: $serviceAccount
    extraArgs:
      - --site-certificate-issuer=stack-default-certificate-issuer

  rbac:
    create: false

  # enable metering for marketplace
  metering:
    gcp:
      secretName: $reportingSecret
      serviceName: presslabs-dashboard.mp-press-labs-public.appspot.com
