# override chart name
fullnameOverride: "${name}"

letsencrypt:
  enabled: false
  email: ""
  server: "https://acme-v02.api.letsencrypt.org/directory"
  # TODO

wordpress-operator:
  enabled: true
  image: $wordpressOperatorImage:${tag}
  extraArgs:
    - --git-clone-image=$wordpressGitCloneImage:${tag}
    - --rclone-image=$wordpressRcloneImage:${tag}
    - --wordpress-runtime-image=$wordpressRuntimeImage
  crd:
    install: true
  rbac:
    create: false
  serviceAccount:
    create: false
    name: $serviceAccount

mysql-operator:
  enabled: true
  image: $mysqlControllerImage:${tag}
  sidecarImage: $mysqlSidecarImage:${tag}
  installCRDs: true
  extraArgs:
    - --metrics-exporter-image=$mysqlMetricsImage:${tag}
    # this list should be keept in sync Makefile image versions and with
    # https://github.com/presslabs/mysql-operator/blob/master/pkg/util/constants/constants.go#L87
    - --mysql-versions-to-image=5.7.26=$mysqlPerconaImage:5.7.26
    # this is set to avoid id collision because of a mysql-operator bug #368
    - --leader-election-id=mysql-operator-leader-election
  rbac:
    create: false
    serviceAccountName: $serviceAccount
  orchestrator:
    image: $mysqlOrchestratorImage:${tag}
    topologyPassword: $mysqlOrchestratorPassword

nginx-ingress:
  enabled: true
  rbac:
    create: false
  serviceAccount:
    create: false
    name: $serviceAccount
  controller:
    image:
      repository: $ingressImage
      # pin version here because it uses comparSemver in chart, patch it later with kustomize
      tag: v0.24.1
  defaultBackend:
    image:
      repository: $ingressDefaultBackendImage
      tag: ${tag}
      pullPolicy: Always

cert-manager:
  enabled: true
  fullnameOverride: ${name}-cert-mgr
  global:
    rbac:
      create: false

  webhook:
    fullnameOverride: ${name}-cert-wh
    image:
      repository: $certWebhookImage
      tag: ${tag}
    global:
      rbac:
        create: false
    serviceAccount:
      create: false
      name: $serviceAccount

  cainjector:
    fullnameOverride: ${name}-cert-inj
    image:
      repository: $certCAinjectorImage
      tag: ${tag}
    global:
      rbac:
        create: false
    serviceAccount:
      create: false
      name: $serviceAccount

  image:
    repository: $certManagerImage
    tag: ${tag}
  extraArgs:
    - --acme-http01-solver-image=$certAcmeSolverImage:${tag}
  serviceAccount:
    create: false
    name: $serviceAccount


prometheus-operator:
  enabled: true
  fullnameOverride: ${name}-prom
  defaultRules:
    create: false
  global:
    rbac:
      create: false
      pspEnabled: false
  alertmanager:
    enabled: false
    serviceAccount:
      create: false
      name: $serviceAccount
  grafana:
    enabled: false
  kubeApiServer:
    enabled: false
  kubelet:
    enabled: false
  kubeControllerManger:
    enabled: false
  coreDns:
    enabled: false
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeStateMetrics:
    enabled: false
  kube-state-metrics:
    rbac:
      create: false
    podSecurityPolicy:
      enabled: false
  nodeExporter:
    enabled: false
  prometheusOperator:
    serviceAccount:
      create: false
      name: $serviceAccount
    createCustomResource: true
    image:
      repository: $promOperatorImage
      tag: ${tag}
    configmapReloadImage:
      repository: $promConfigMapReloadImage
      tag: ${tag}
    prometheusConfigReloaderImage:
      repository: $promConfigReloaderImage
      tag: ${tag}

  prometheus:
    serviceAccount:
      create: false
      name: $serviceAccount
    prometheusSpec:
      image:
        repository: $promImage
        # pin version here because it is used as version and patch with kustomize tag field
        tag: v2.9.1
