stack:
  # override chart name
  fullnameOverride: "${name}"

  letsencrypt:
    enabled: true
    email: $letsEncryptEmail
    server: $letsEncryptServer

  wordpress-operator:
    enabled: true
    image: $wordpressOperatorImage
    crd:
      install: true
    rbac:
      create: false
    serviceAccount:
      create: false
      name: $serviceAccount

  mysql-operator:
    enabled: true
    image: $mysqlControllerImage
    installCRDs: true
    extraArgs:
      # this is set to avoid id collision because of a mysql-operator bug #368
      - --leader-election-id=mysql-operator-leader-election
    rbac:
      create: false
      serviceAccountName: $serviceAccount
    orchestrator:
      image: $mysqlOrchestratorImage
      # NOTE: this will be ovewrite by kustomize
      topologyPassword: SET_IN_KUSTOMIZE

  nginx-ingress:
    enabled: true
    rbac:
      create: false
    serviceAccount:
      create: false
      name: $serviceAccount
    controller:
      image:
        repository: $ingressImageRegistry
        # pin version here because it uses comparSemver in chart, patch it later with kustomize
        tag: v0.24.1
    defaultBackend:
      image:
        repository: $ingressDefaultBackendImageRegistry
        tag: $ingressDefaultBackendImageTag
        pullPolicy: Always

  cert-manager:
    enabled: true
    fullnameOverride: ${name}-cert-manager
    global:
      rbac:
        create: false

    webhook:
      fullnameOverride: ${name}-cert-manager-webhook
      image:
        repository: $certWebhookImageRegistry
        tag: $certWebhookImageTag
      global:
        rbac:
          create: false
      serviceAccount:
        create: false
        name: $serviceAccount

    cainjector:
      fullnameOverride: ${name}-cert-manager-cainjector
      image:
        repository: $certCAinjectorImageRegistry
        tag: $certCAinjectorImageTag
      global:
        rbac:
          create: false
      serviceAccount:
        create: false
        name: $serviceAccount

    image:
      repository: $certManagerImageRegistry
      tag: $certManagerImageTag
    extraArgs:
      - --acme-http01-solver-image=$certAcmeSolverImage
    serviceAccount:
      create: false
      name: $serviceAccount


  prometheus-operator:
    enabled: true
    fullnameOverride: ${name}-prometheus
    defaultRules:
      create: false
    global:
      rbac:
        create: false
        pspEnabled: false
    alertmanager:
      enabled: false
      serviceAccount:
        create: false
        name: $serviceAccount
    grafana:
      enabled: false
    kubeApiServer:
      enabled: false
    kubelet:
      enabled: false
    kubeControllerManger:
      enabled: false
    coreDns:
      enabled: false
    kubeDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeStateMetrics:
      enabled: false
    kube-state-metrics:
      rbac:
        create: false
      podSecurityPolicy:
        enabled: false
    nodeExporter:
      enabled: false
    prometheusOperator:
      serviceAccount:
        create: false
        name: $serviceAccount
      createCustomResource: true
      image:
        repository: $promOperatorImageRegistry
        tag: $promOperatorImageTag
    prometheus:
      serviceAccount:
        create: false
        name: $serviceAccount


dashboard:
  image: $dashboardImage
  fullNameOverride: "${name}-dashboard"

  defaults:
    installRoles: true

  crd:
    install: true

  gcloud:
    projectID: $dashboardProjectID
    # NOTE: those valus is patched by kustomize
    serviceAccountKey: SET_IN_KUSTOMIZE

  apiserver:
    oidc:
      # NOTE: those valuse are patched by kustomize
      client_id: SET_IN_KUSTOMIZE
      client_secret: SET_IN_KUSTOMIZE
      client_issuer: SET_IN_KUSTOMIZE

    baseURL: //$dashboardDomain

    sentryDSN: SET_IN_KUSTOMIZE

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/cluster-issuer: ${name}-default
        certmanager.k8s.io/acme-challenge-type: http01
      hosts:
        - $dashboardDomain
      tls:
        - secretName: ${name}-dashboard-tls
          hosts:
            - $dashboardDomain
    serviceAccount:
      create: false
      name: $serviceAccount

  controller:
    serviceAccount:
      create: false
      name: $serviceAccount
    extraArgs:
      - --site-certificate-issuer=${name}-default

  rbac:
    create: false

  # enable metering for marketplace
  metering:
    gcp:
      secretName: $reportingSecret
      serviceName: dummy #TODO: this should be filled in later when it's available
