# resources that will be deployed by the job
resources:
  # stack
  - namespace.yaml

  # crds
  - ../charts/dashboard-gcm/charts/dashboard/templates/crds.yaml

  # dashboard
  - ../charts/dashboard-gcm/charts/dashboard/templates/default-roles.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/default-role-bindings.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/prometheus-clusterrole.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/invite-clusterrole.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/default-priority-classes.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/storage-class-ssd.yaml

  # webhooks and its certificates and issuers
  - ../charts/dashboard-gcm/charts/dashboard/templates/webhook.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/webhook-pki.yaml


patchesJson6902:
# dashboard
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: ValidatingWebhookConfiguration
    name: ${name}-dashboard
  path: owner_reference_patch.yaml

# certificates
- target:
    group: cert-manager.io
    version: v1alpha2
    kind: Certificate
    name: ${name}-dashboard-webhook
    namespace: ${namespace}
  path: owner_reference_patch.yaml

- target:
    group: cert-manager.io
    version: v1alpha2
    kind: Issuer
    name: ${name}-dashboard-webhook-ca
    namespace: ${namespace}
  path: owner_reference_patch.yaml

- target:
    group: cert-manager.io
    version: v1alpha2
    kind: Certificate
    name: ${name}-dashboard-webhook-ca
    namespace: ${namespace}
  path: owner_reference_patch.yaml

- target:
    group: cert-manager.io
    version: v1alpha2
    kind: Issuer
    name: ${name}-dashboard-webhook-ca-issuer
    namespace: ${namespace}
  path: owner_reference_patch.yaml


commonLabels:
  app.kubernetes.io/name: presslabs-dashboard
  app.kubernetes.io/instance: ${name}
  app.kubernetes.io/version: "1.0.0"
