# resources that will be deployed by the job
resources:
  # dashboard
  - ../charts/dashboard-gcm/charts/dashboard/templates/default-roles.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/default-role-bindings.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/prometheus-clusterrole.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/invite-clusterrole.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/default-priority-classes.yaml

  - ../charts/dashboard-gcm/charts/dashboard/templates/webhook.yaml
  - ../charts/dashboard-gcm/charts/dashboard/templates/webhook-pki.yaml

  # stack
  - ../charts/dashboard-gcm/charts/stack/templates/acme-issuer.yaml

  # cert manager
  - ../charts/dashboard-gcm/charts/stack/charts/cert-manager/templates/webhook-apiservice.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/cert-manager/templates/webhook-validating-webhook.yaml
  - ../charts/dashboard-gcm/charts/stack/charts/cert-manager/templates/webhook-mutating-webhook.yaml


patchesJson6902:
# cert-manager set owner reference
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: ValidatingWebhookConfiguration
    name: ${name}-cert-manager-webhook
  path: owner_reference_patch.yaml
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: MutatingWebhookConfiguration
    name: ${name}-cert-manager-webhook
  path: owner_reference_patch.yaml
- target:
    group: apiregistration.k8s.io
    version: v1beta1
    kind: APIService
    name: v1beta1.webhook.cert-manager.io
  path: owner_reference_patch.yaml

# dashboard
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: ValidatingWebhookConfiguration
    name: ${name}-dashboard
  path: owner_reference_patch.yaml

- target:
    group: scheduling.k8s.io
    version: v1beta1
    kind: PriorityClass
    name: presslabs-dashboard-memcached
  path: owner_reference_patch.yaml

- target:
    group: scheduling.k8s.io
    version: v1beta1
    kind: PriorityClass
    name: presslabs-dashboard-database
  path: owner_reference_patch.yaml

# stack
- target:
    group: cert-manager.io
    version: v1alpha2
    kind: ClusterIssuer
    name: ${name}-default
  path: owner_reference_patch.yaml

# certificates
- target:
    group: cert-manager.io
    version: v1alpha2
    kind: Certificate
    name: ${name}-ingress-default
  path: owner_reference_patch.yaml
- target:
    group: cert-manager.io
    version: v1alpha2
    kind: Certificate
    name: ${name}-dashboard-webhook
    namespace: ${namespace}
  path: owner_reference_patch.yaml

- target:
    group: cert-manager.io
    version: v1alpha2
    kind: Issuer
    name: ${name}-dashboard-webhook-ca
    namespace: ${namespace}
  path: owner_reference_patch.yaml

- target:
    group: cert-manager.io
    version: v1alpha2
    kind: Certificate
    name: ${name}-dashboard-webhook-ca
    namespace: ${namespace}
  path: owner_reference_patch.yaml

- target:
    group: cert-manager.io
    version: v1alpha2
    kind: Issuer
    name: ${name}-dashboard-webhook-ca-issuer
    namespace: ${namespace}
  path: owner_reference_patch.yaml


commonLabels:
  app.kubernetes.io/name: presslabs-dashboard
  app.kubernetes.io/instance: ${name}
  app.kubernetes.io/version: "0.0.1"
